### PR TITLE
MM-29720 - Consistently track Mattermost User ID aross telemetry events

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Does what it says.
- Couldn't fix all of Eric's problems in https://docs.google.com/document/d/1X7VK9El-WjXKzsQY8CVzcOmATkodIjtFBXWpUuESfoI/edit# . Will see if the next ticket can do it.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-29720

### CODE REVIEW

**Review by agarciamontoro — COMMENTED** [review]
The code looks perfect!

But I don't know why we need this information, actually. The original idea for the telemetry was not to identify anyone, just having a bird's eye view of the actions performed. This breaks that assumption. This would be something to discuss with @itao and @enelson720, I guess.

**Comment by cpoile** [comment]
@agarciamontoro It's so that the analytics scripts can collate everything correctly, see: https://docs.google.com/document/d/1X7VK9El-WjXKzsQY8CVzcOmATkodIjtFBXWpUuESfoI/edit#heading=h.nku49ruh4rqq

**Comment by itao** [comment]
We initially made the assumption to not identify anyone when this product was intended for on-prem customer only, but the Cloud product has since then came into existence. Would it be feasible to configure telemetry based on where it's deployed and user opt-in? Ie. collect full set of info for Cloud and on-prem customers that opted in for telemetry but not for on-prem customers that did not opt-in?

**Comment by cpoile** [comment]
@itao For the on-prem non-opt-in customers, what would we collect? (if anything)

**Comment by itao** [comment]
@cpoile I just confirmed that telemetry for on-prem customers is opt-out. So for those that have opted out, we would not collect anything.

**Comment by cpoile** [comment]
Waiting on the decision from legal and bizops about whether we should be tracking `ActualUserId` from cloud accounts. (cc: @itao)

**Comment by itao** [comment]
@cpoile Here's the MM post to close the loop on this decision: https://community-release.mattermost.com/private-core/pl/r5fri1whrin8trfpi1u37yqrzh

**Comment by cpoile** [comment]
Awesome, thanks!  @agarciamontoro and @crspeller ready for review. https://github.com/mattermost/mattermost-plugin-api/pull/77 means turning-off diagnostics in the system control panel actually turns off our telemetry now. :)

**Review by crspeller — APPROVED** [review]

**Review by agarciamontoro — APPROVED** [review]
Thank you!

**Pull request merged**
