### PR TITLE
MM-28174 - Wrap task labels

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Before:
image

- After:
image

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-28174

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Review by agarciamontoro — APPROVED** [review]
Approving this, but I *think* it would be better to align the checkbox to the top of the text. Have you tried that?

**Comment by cpoile** [comment]
I thought about it, but I'll leave it to Asaad. :)

**Comment by cpoile** [comment]
@asaadmahmood Gentle ping. :)

**Comment by asaadmahmood** [comment]
@cpoile I agree, lets align the checkboxes to the top.

**Comment by cpoile** [comment]
@asaadmahmood Okay, looks like: 
image

Do you want a bit of padding on the top of the checkbox?  (Or, feel free to fiddle with it yourself!)

**Review by asaadmahmood — APPROVED** [review]
LGTM, I may fiddle with it when I am making any other changes in the UI (as a separate effort).

**Comment by asaadmahmood** [comment]
Also we should say Tasks instead of Checklist, but we can do a complete copy review later as well.

**Pull request merged**
